# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViVNewsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViVNewsApp
  pod 'Alamofire', '~> 4.9.0'
  pod 'AlamofireImage', '~> 3.5.2'
  pod 'NVActivityIndicatorView', '~> 4.8.0'

end
